name: Build and deploy Javadoc

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build javadoc
      run: mvn javadoc:javadoc
      
    - name: Deploy javadoc to its assigned branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: javadoc
        FOLDER: target/site/apidocs
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLEAR_GLOBS_FILE: ".github/javadoc-publish-clear"
